import type { Daypart, Locale } from "@/types";

export const copy = {
  tr: {
    product: "Üretken Yüz Kası Klavyesi",
    heroLead: "Kavram Odaklı Web-AAC Sistemi",
    heroBody:
      "Minimum hareket, eksiksiz iletişim. Yüz kaslarınızla saniyeler içinde doğal cümleler kurun.",
    start: "İletişimi Başlat",
    awaitingPermission: "İzin bekleniyor...",
    disclaimer:
      "Yasal Uyarı: Bu sistem bir iletişim destek aracıdır (AAC), medikal bir teşhis veya tedavi cihazı değildir.",
    scrollTop: "Yukarı çık",
    docs: "Dokümantasyon",
    care: "Bakım ve Takip Paneli",
    careEmpty: "Kayıt yok.",
    careAll: "Tümü",
    careSentences: "Cümleler",
    careAlerts: "Uyarılar",
    careNotesFilter: "Notlar",
    careRecords: "Kayıtlar",
    careClear: "Kayıtları temizle",
    careClearConfirm: "Panel kayıtları silinsin mi? Adlar ve notlar kalır.",
    careKindSentence: "Cümle",
    careKindSos: "SOS",
    careKindAlarm: "Acil alarm",
    careKindNote: "Sesli not",
    careKeywords: "Kelimeler",
    userNameLabel: "Kullanıcı",
    caregiverNameLabel: "Bakım veren",
    userNamePlaceholder: "Ad-Soyad",
    caregiverNamePlaceholder: "Ad-Soyad",
    notesTitle: "Sesli notlar",
    notesTextLabel: "Not",
    notesDateLabel: "Tarih",
    notesTimeLabel: "Saat",
    notesAdd: "Ekle",
    notesDelete: "Sil",
    notesPlay: "Şimdi oku",
    notesEnabled: "Aktif",
    copyright: "© 2026 Üretken Yüz Kası Klavyesi. Tüm hakları saklıdır.",
    docsLead:
      "Güvenli ve yormayan bir iletişim destek sistemi. Nasıl çalıştığı aşağıda.",
    docsConceptTitle: "Hızlı ve Doğal İletişim",
    docsConceptBody:
      "Harf harf yazarak yorulmanıza gerek yoktur. Sadece temel kelimeleri seçin, sistem sizin için saniyeler içinde anlamlı ve doğal cümleler kursun.",
    docsPrivacyTitle: "Gizlilik",
    docsPrivacyBody:
      "Kamera görüntüsü bu sekmede işlenir ve sunucuya gönderilmez. Cümle üretimi yalnızca seçilen kelimeleri kullanır.",
    docsSafetyTitle: "Bakıcı Çağrısı (Fail-Safe)",
    docsSafetyBody:
      "Gerektiğinde 6 saniye içinde üst üste 3 kez uzun göz kırparak bakıcınıza veya yakınlarınıza anında sesli çağrı gönderebilirsiniz.",
    docsMasseterTitle: "Yorulmayan Kullanım",
    docsMasseterBody:
      "Sistem, gün içinde en geç yorulan kas grubuna (masseter / çiğneme kası) göre tasarlanmıştır. Göz kırpmak yerine hafif bir çene sıkma hareketiyle hiç yorulmadan seçim yapabilirsiniz.",
    docsBaselineTitle: "Akıllı Spazm Filtresi",
    docsBaselineBody:
      "Kamera açıldığında sistem önce yüzünüzü tanır ve istemsiz hareketlerinizi (spazm) öğrenir. Böylece istem dışı mimiklerin yanlışlıkla kelime seçmesini engeller.",
    docsPaceTitle: "Acele Etmeden Seçim",
    docsPaceBody:
      "Klinik bulgulara uygun olarak, sistem seçim yapmadan önce size düşünmeniz için yeterli zamanı (5-8 saniye) tanır. Sizi asla acele ettirmez.",
    docsSleepTitle: "Dinlenme Modu",
    docsSleepBody:
      "Sistemi kullanmadığınız anlarda yüzünüzü dinlendirmek için cihazı uyku moduna alabilirsiniz. Bu modda sadece acil durum alarmı aktif kalır, diğer hareketleriniz yoksayılır.",
    docsSosTitle: "Hayati Acil Durum Alarmı (SOS)",
    docsSosBody:
      "Nefes darlığı gibi panik anlarında (gözlerin aniden genişlemesi vb.), sistem bunu otomatik algılar ve çevrenizdekilere sesli Solunum/Yutma Güçlüğü acil durum uyarısı verir.",
    featureBrowser: "Tarayıcıda çalışır",
    featureBrowserBody: "Kurulum yok. Yüz görüntüsü bu sekmede kalır.",
    featureZero: "Seçilen kelimeler",
    featureZeroBody: "Cümleye yalnızca seçtiğin kelimeler girer.",
    featurePersonal: "Kişiselleştirilebilir",
    featurePersonalBody:
      "Saat, dil ve bakım panelindeki en fazla 8 bağlam kelimesi ızgarayı kişiye göre dizer.",
    startHint: "Kamera görüntüsü bu cihazda işlenir.",
    loadingModel: "Yüz ağı yükleniyor…",
    awaitingFace: "Yüzünüzü çerçeveye alın",
    calibrating: "Yüzünüzü çerçevede tutun",
    live: "Canlı",
    noCamera:
      "Kamera alınamadı. Chrome veya Edge kullanın, izin verin, ardından yenileyin.",
    noModel:
      "Yüz ağı yüklenemedi. Space tuşu ile ızgarayı kullanabilirsiniz.",
    retry: "Yeniden dene",
    keywords: "Anahtar kelimeler",
    keywordsEmpty: "Kısa göz kırpma ile anahtar kelime ekleyin",
    keywordsEmptyJaw: "Çene sıkma ile anahtar kelime ekleyin",
    keywordRemove: "Bu kelimeyi çıkar",
    sentence: "Cümle",
    sentenceEmpty: "Üret’e seçince seçilen kelimeler tek cümleye döner",
    speaking: "Seslendiriliyor",
    generating: "Cümle hazırlanıyor…",
    fallback: "Yerel yedek",
    blink: "Kısa kırp = seç",
    jawHint: "Çene sıkma = seç",
    space: "Space = yedek tıklama",
    longBlink: "3 kez uzun kırp = bakıcı çağrısı",
    esc: "Esc veya çene = alarmı iptal et",
    settingsTitle: "Erişilebilirlik ayarları",
    triggerLabel: "Kontrol Yöntemi",
    triggerJaw: "Çene sıkma ile seçim (masseter / çiğneme kası)",
    triggerJawHint: "Uzun süreli ve yorulmadan kullanım için idealdir.",
    triggerBlink: "Göz kırpma ile seçim",
    triggerBlinkHint: "Kısa bir göz kırpma hareketiyle seçim yapmanızı sağlar.",
    recommended: "Önerilen",
    scanLabel: "Seçim onay süresi",
    scanHint: "Sistemin bir seçimi onaylamadan önce sizi bekleyeceği süre.",
    scanUnit: "sn",
    jawMeter: "Çene",
    eyelidMeter: "Göz kapağı yükselmesi",
    baselineTitle: "Hazırlık",
    baselineBody:
      "Sistem kişisel yüz hareketlerinizi analiz ediyor... Lütfen 5 saniye normal pozisyonunuzda bekleyin.",
    sleepTitle: "Dinlenme modu",
    sleepHint:
      "Seçim duraklatılır; acil durum alarmı açık kalır. Gözler 5 saniye kapalı tutulursa aynı moda geçilir.",
    sleepWake: "Sisteme dön",
    sleepWakeHint: "Çene 3 saniye sıkılı tutulduğunda da dinlenme modundan çıkılır.",
    sleepCaption: "Dinlenme modu etkin. Seçim ızgarası duraklatıldı.",
    sosTitle: "Acil durum (SOS)",
    sosBody: "Solunum sıkıntısı / yutma güçlüğü bildirildi.",
    sosBreath: "Solunum sıkıntısı.",
    sosSwallow: "Yutma güçlüğü.",
    sosReasonLid: "Ani göz kapağı yükselmesi algılandı.",
    sosReasonJaw: "Uzun süreli çene sıkma algılandı.",
    meshOn: "Yüz ağı açık",
    fps: "FPS",
    openness: "Göz açıklığı",
    safety: "Bakıcı çağrısı",
    graceTitle: "Acil durum iptal penceresi",
    graceBody:
      "Üst üste 3 uzun göz kırpma algılandı. İstemediyseniz şimdi iptal edin.",
    cancel: "İPTAL",
    alarmTitle: "Acil durum alarmı",
    alarmBody: "Bakıcı bildirimi gönderildi.",
    emergencyCancelHint:
      "İptal: çenenizi sıkın, Esc'ye basın veya İPTAL düğmesine dokunun.",
    callCaregiver: "Bakıcıyı ara",
    caregiverPhoneLabel: "Bakıcı telefonu",
    caregiverPhonePlaceholder: "+90 …",
    caregiverPhoneHint:
      "Acil durumda bu numarayı ara düğmesi açar. Numara yalnızca bu cihazda saklanır.",
    protocolKicker: "Başlangıç kontrolü",
    protocolTitle: "Kamera açılmadan önce",
    protocolLead:
      "Ortamı ve güvenlik yolunu bir kez netleştirin. Yüz görüntüsü bu sekmede işlenir; sunucuya gönderilmez.",
    protocolLightTitle: "Aydınlatma",
    protocolLight: "Yüz önden ve dengeli ışıkta olsun. Arkadan gelen güçlü ışık tanımayı bozar.",
    protocolFaceTitle: "Çerçeve",
    protocolFace: "Gözler ile çene görünür, yüz kamerayı doldurur.",
    protocolControlTitle: "Seçim yöntemi",
    protocolControlJaw: "Çene sıkma (masseter / çiğneme kası). Uzun süreli kullanım için önerilen yöntem.",
    protocolControlBlink: "Kısa göz kırpma ile seçim.",
    protocolCaregiverTitle: "Bakım veren",
    protocolCaregiver: "Bakım veren bu odada veya telefonla ulaşılabilir durumda.",
    protocolCarePhone: "Kayıtlı numara",
    protocolSafetyTitle: "Bakıcı çağrısı",
    protocolSafety:
      "Altı saniye içinde üç uzun göz kırpma çağrıyı başlatır. Yanlış tetiklenirse çenenizi sıkın, Esc’ye basın veya İPTAL’e dokunun.",
    protocolNotify: "Bu cihazda bakıcı bildirimlerine izin ver",
    protocolNotifyOn: "Bu cihazda bildirimler açık",
    protocolStart: "İletişimi başlat",
    protocolCancel: "Vazgeç",
    vocabTitle: "Kişisel bağlam kelimeleri",
    vocabHint:
      "Temel ihtiyaçlar ızgarada sabittir. Bu kişi için en fazla sekiz bağlam kelimesi seçilir; seçilmezse kalan yerler günün saatine göre düzenlenir.",
    vocabCustom: "Özel kelime",
    vocabCustomAdd: "Ekle",
    summaryTitle: "Bugünkü oturum özeti",
    summaryDate: "Tarih",
    summaryPrint: "Yazdır",
    summaryFileLabel: "Dosya adı",
    languageToEn: "İngilizceye geç",
    languageToTr: "Türkçeye geç",
    fullscreenEnter: "Tam ekran",
    fullscreenExit: "Tam ekrandan çık",
    liveAlertTitle: "Canlı uyarı",
    webhookReady: "Uzak bakıcı bildirimi (webhook) sunucuda tanımlı.",
    webhookMissing:
      "Uzak webhook tanımlı değil; bildirim bu tarayıcı ve telefon düğmesi ile çalışır.",
    docsProtocolTitle: "İlk oturum protokolü",
    docsProtocolBody:
      "Kamera açılmadan önce aydınlatma, çerçeve, seçim yöntemi, bakım veren erişimi ve bakıcı çağrısı yolu netleştirilir.",
    docsVocabTitle: "Kişisel ızgara",
    docsVocabBody:
      "Bakım paneli en fazla 8 bağlam kelimesi seçer. Çekirdek ihtiyaç satırı değişmez; kalan hücreler gün dilimine göre dolar.",
    docsKioskTitle: "Odaklı kullanım",
    docsKioskBody:
      "Oturum açıkken ekran uyanık tutulur, tam ekran önerilir ve sekmeyi kapatmadan önce uyarı çıkar. Tarayıcı menüsünden ana ekrana eklenebilir.",
    docsNoticeTitle: "Bakıcı uyarısı",
    docsNoticeBody:
      "SOS ve bakıcı çağrısında bu sekmede sesli uyarı, isteğe bağlı tarayıcı bildirimi ve telefonla ara düğmesi açılır. İstenirse uzak bakıcı sistemine de sinyal gönderilebilir.",
    privacy: "Gizlilik",
    privacyHeading: "Gizlilik Bildirimi",
    privacyIntro: "Bu bildirim, kişisel verilerin nasıl işlendiğini açıklar.",
    privacyLead: "Kişisel bilgiler ve oturum kayıtları bu cihazda tutulur.",
    privacyCameraTitle: "Kamera",
    privacyCameraBody:
      "Yüz işleme tarayıcı içinde yapılır. Kamera görüntüsü iletilmez ve saklanmaz.",
    privacyStoreTitle: "Yerel kayıtlar",
    privacyStoreBody:
      "Ad, telefon, kelime tercihleri ve oturum kayıtları yalnızca bu tarayıcıda tutulur. Cihazlar arasında eşitlenmez.",
    privacyLlmTitle: "Cümle üretimi",
    privacyLlmBody:
      "Cümle üretiminde yalnızca seçilen anahtar kelimeler iletilir. Kamera görüntüsü gönderilmez. Üretim hizmeti tanımlı değilse cümle bu cihazda kurulur.",
    privacyAlertTitle: "Bakıcı uyarısı",
    privacyAlertBody:
      "SOS ve bakıcı çağrısı bu tarayıcıda sesli uyarı üretir. Telefon numarası yerel tutulur. Uzak bildirim yalnızca sunucuda bir alıcı tanımlıysa gönderilir.",
    daypart: {
      morning: "Sabah bağlamı",
      afternoon: "Öğle bağlamı",
      evening: "Akşam bağlamı",
      night: "Gece bağlamı",
    } satisfies Record<Daypart, string>,
    uspHint: "Su + Soğuk → Soğuk su istiyorum. (seçilmeyen hiçbir şey eklenmez)",
  },
  en: {
    product: "Generative Facial Muscle Keyboard",
    heroLead: "Concept-focused Web-AAC system",
    heroBody:
      "Minimal movement, complete communication. Form natural sentences in seconds with your facial muscles.",
    start: "Start communication",
    awaitingPermission: "Waiting for permission...",
    disclaimer:
      "Legal notice: This system is an AAC communication aid, not a medical diagnostic or treatment device.",
    scrollTop: "Back to top",
    docs: "Documentation",
    care: "Care and Follow-up Panel",
    careEmpty: "No records.",
    careAll: "All",
    careSentences: "Sentences",
    careAlerts: "Alerts",
    careNotesFilter: "Notes",
    careRecords: "Records",
    careClear: "Clear entries",
    careClearConfirm: "Delete panel entries? Names and notes are kept.",
    careKindSentence: "Sentence",
    careKindSos: "SOS",
    careKindAlarm: "Emergency alarm",
    careKindNote: "Voice note",
    careKeywords: "Keywords",
    userNameLabel: "User",
    caregiverNameLabel: "Caregiver",
    userNamePlaceholder: "Full name",
    caregiverNamePlaceholder: "Full name",
    notesTitle: "Voice notes",
    notesTextLabel: "Note",
    notesDateLabel: "Date",
    notesTimeLabel: "Time",
    notesAdd: "Add",
    notesDelete: "Delete",
    notesPlay: "Read now",
    notesEnabled: "Active",
    copyright: "© 2026 Üretken Yüz Kası Klavyesi. Tüm hakları saklıdır.",
    docsLead:
      "A safe, low-fatigue communication aid. How it works is below.",
    docsConceptTitle: "Fast and Natural Communication",
    docsConceptBody:
      "You do not need to spell letter by letter. Select only the core words; the system forms meaningful, natural sentences for you in seconds.",
    docsPrivacyTitle: "Privacy",
    docsPrivacyBody:
      "Camera frames are processed in this tab and never uploaded. Sentence generation uses only the words you pick.",
    docsSafetyTitle: "Caregiver Call (Fail-Safe)",
    docsSafetyBody:
      "When needed, three long blinks within 6 seconds send an immediate spoken call to your caregiver or family.",
    docsMasseterTitle: "Fatigue-Free Use",
    docsMasseterBody:
      "The system is designed around the muscle group that tires last during the day (masseter / chewing muscle). Instead of blinking, a light jaw clench lets you select without fatigue.",
    docsBaselineTitle: "Smart Spasm Filter",
    docsBaselineBody:
      "When the camera opens, the system first learns your face and involuntary movements (spasms). This keeps unintentional expressions from selecting a word by mistake.",
    docsPaceTitle: "Unhurried Selection",
    docsPaceBody:
      "In line with clinical findings, the system gives you enough time to think (5-8 seconds) before a selection. It never rushes you.",
    docsSleepTitle: "Rest Mode",
    docsSleepBody:
      "When you are not using the system, you can put the device to sleep to rest your face. Only the emergency alarm stays active; other movements are ignored.",
    docsSosTitle: "Vital Emergency Alarm (SOS)",
    docsSosBody:
      "In moments of panic such as shortness of breath (sudden eye widening, and similar cues), the system detects this automatically and speaks a Breathing/Swallowing Difficulty emergency alert to those nearby.",
    featureBrowser: "Runs in the browser",
    featureBrowserBody: "No install. Face video never leaves this tab.",
    featureZero: "Selected words only",
    featureZeroBody: "Only the words you select enter the sentence.",
    featurePersonal: "Personalizable",
    featurePersonalBody:
      "Time of day, language, and up to eight care-panel context words reshape the grid.",
    startHint: "Camera video is processed on this device.",
    loadingModel: "Loading face mesh…",
    awaitingFace: "Align your face in the frame",
    calibrating: "Keep your face in the frame",
    live: "Live",
    noCamera:
      "Camera unavailable. Use Chrome or Edge, allow access, then retry.",
    noModel: "Face mesh failed to load. You can still drive the grid with Space.",
    retry: "Retry",
    keywords: "Keywords",
    keywordsEmpty: "Short blink to add a keyword",
    keywordsEmptyJaw: "Jaw clench to add a keyword",
    keywordRemove: "Remove this word",
    sentence: "Sentence",
    sentenceEmpty: "Select Generate to turn keywords into one sentence",
    speaking: "Speaking",
    generating: "Preparing the sentence…",
    fallback: "Local fallback",
    blink: "Short blink = select",
    jawHint: "Jaw clench = select",
    space: "Space = backup click",
    longBlink: "3 long blinks = caregiver call",
    esc: "Esc or jaw = cancel alarm",
    settingsTitle: "Accessibility settings",
    triggerLabel: "Control Method",
    triggerJaw: "Select with jaw clench (masseter / chewing muscle)",
    triggerJawHint: "Ideal for long sessions without fatigue.",
    triggerBlink: "Select with blink",
    triggerBlinkHint: "Lets you select with a short blink.",
    recommended: "Recommended",
    scanLabel: "Selection confirmation time",
    scanHint: "How long the system waits for you before confirming a selection.",
    scanUnit: "s",
    jawMeter: "Jaw",
    eyelidMeter: "Eyelid raise",
    baselineTitle: "Getting ready",
    baselineBody:
      "The system is learning your usual facial motion… Please hold your normal resting expression for 5 seconds.",
    sleepTitle: "Rest mode",
    sleepHint:
      "Selection pauses; the emergency alarm stays on. Closing the eyes for 5 seconds also enters this mode.",
    sleepWake: "Return to the system",
    sleepWakeHint: "A 3-second jaw clench also exits rest mode.",
    sleepCaption: "Rest mode is on. The selection grid is paused.",
    sosTitle: "Emergency (SOS)",
    sosBody: "Breathing difficulty / swallowing difficulty reported.",
    sosBreath: "Breathing difficulty.",
    sosSwallow: "Swallowing difficulty.",
    sosReasonLid: "Sudden eyelid raise detected.",
    sosReasonJaw: "Prolonged jaw clench detected.",
    meshOn: "Face mesh on",
    fps: "FPS",
    openness: "Eye openness",
    safety: "Caregiver call",
    graceTitle: "Emergency grace period",
    graceBody: "Three long blinks in a row were detected. Cancel now if this was accidental.",
    cancel: "CANCEL",
    alarmTitle: "Emergency alarm",
    alarmBody: "Caregiver notice sent.",
    emergencyCancelHint: "Cancel: clench your jaw, press Esc, or tap CANCEL.",
    callCaregiver: "Call caregiver",
    caregiverPhoneLabel: "Caregiver phone",
    caregiverPhonePlaceholder: "+90 …",
    caregiverPhoneHint:
      "Emergency screens open a call button for this number. The number stays on this device only.",
    protocolKicker: "Start check",
    protocolTitle: "Before the camera opens",
    protocolLead:
      "Confirm the room and the safety path once. Face video is processed in this tab and is never uploaded.",
    protocolLightTitle: "Lighting",
    protocolLight: "The face is lit from the front, evenly. Strong light from behind disrupts recognition.",
    protocolFaceTitle: "Frame",
    protocolFace: "The eyes and jaw are visible, and the face fills the camera.",
    protocolControlTitle: "Control method",
    protocolControlJaw: "Jaw clench (masseter / chewing muscle). The recommended method for long sessions.",
    protocolControlBlink: "Selection with a short blink.",
    protocolCaregiverTitle: "Caregiver",
    protocolCaregiver: "A caregiver is in the room or reachable by phone.",
    protocolCarePhone: "Saved number",
    protocolSafetyTitle: "Caregiver call",
    protocolSafety:
      "Three long blinks within six seconds start the call. If it was accidental, clench the jaw, press Esc, or tap CANCEL.",
    protocolNotify: "Allow caregiver notifications on this device",
    protocolNotifyOn: "Notifications are on for this device",
    protocolStart: "Start communication",
    protocolCancel: "Cancel",
    vocabTitle: "Personal context words",
    vocabHint:
      "Core needs stay on the grid. Up to eight context words can be set for this person; otherwise the remaining cells follow the time of day.",
    vocabCustom: "Custom word",
    vocabCustomAdd: "Add",
    summaryTitle: "Today’s session summary",
    summaryDate: "Date",
    summaryPrint: "Print",
    summaryFileLabel: "File name",
    languageToEn: "Switch to English",
    languageToTr: "Switch to Turkish",
    fullscreenEnter: "Full screen",
    fullscreenExit: "Exit full screen",
    liveAlertTitle: "Live alert",
    webhookReady: "Remote caregiver notice (webhook) is configured on the server.",
    webhookMissing:
      "No remote webhook is set; alerts use this browser and the call button.",
    docsProtocolTitle: "First-use protocol",
    docsProtocolBody:
      "Before the camera opens, lighting, framing, control method, caregiver access, and the caregiver-call path are confirmed.",
    docsVocabTitle: "Personal grid",
    docsVocabBody:
      "The care panel selects up to eight context words. The core need row does not change; remaining cells fill by time of day.",
    docsKioskTitle: "Focused use",
    docsKioskBody:
      "While a session is running the screen stays awake, full screen is recommended, and closing the tab warns first. It can be added to the home screen from the browser menu.",
    docsNoticeTitle: "Caregiver alert",
    docsNoticeBody:
      "SOS and caregiver-call events open a spoken alert in this tab, an optional browser notification, and a phone call button. A remote caregiver system can also be signaled if it is configured.",
    privacy: "Privacy",
    privacyHeading: "Privacy Notice",
    privacyIntro: "This notice explains how personal data is handled.",
    privacyLead: "Personal details and session records are kept on this device.",
    privacyCameraTitle: "Camera",
    privacyCameraBody:
      "Face processing runs in the browser. Camera frames are neither transmitted nor stored.",
    privacyStoreTitle: "Local records",
    privacyStoreBody:
      "Names, the phone number, word preferences, and session records are kept in this browser only. They are not synchronized across devices.",
    privacyLlmTitle: "Sentence generation",
    privacyLlmBody:
      "When a sentence is generated, only the selected keywords are sent. Camera frames are not. If no generation service is configured, the sentence is built on this device.",
    privacyAlertTitle: "Caregiver alert",
    privacyAlertBody:
      "SOS and caregiver-call events produce a spoken alert in this browser. The phone number is stored locally. A remote notice is sent only when a recipient is configured on the server.",
    daypart: {
      morning: "Morning context",
      afternoon: "Afternoon context",
      evening: "Evening context",
      night: "Night context",
    } satisfies Record<Daypart, string>,
    uspHint: "Water + Cold → I want cold water. (nothing unselected is added)",
  },
} as const satisfies Record<Locale, object>;

export function t(locale: Locale) {
  return copy[locale];
}
