import type { Word } from "@/types";

/**
 * Core row is always present. Remaining cells are ranked by daypart
 * so breakfast language leads the morning and sleep/light lead the night.
 */
export const VOCABULARY: Word[] = [
  {
    id: "yes",
    tr: "Evet",
    en: "Yes",
    category: "core",
    weights: { morning: 1, afternoon: 1, evening: 1, night: 1 },
  },
  {
    id: "no",
    tr: "Hayır",
    en: "No",
    category: "core",
    weights: { morning: 1, afternoon: 1, evening: 1, night: 1 },
  },
  {
    id: "help",
    tr: "Yardım",
    en: "Help",
    category: "core",
    weights: { morning: 1, afternoon: 1, evening: 1, night: 1 },
  },
  {
    id: "pain",
    tr: "Ağrı",
    en: "Pain",
    category: "core",
    weights: { morning: 1, afternoon: 1, evening: 1, night: 1 },
  },
  {
    id: "toilet",
    tr: "Tuvalet",
    en: "Toilet",
    category: "core",
    weights: { morning: 1, afternoon: 1, evening: 1, night: 1 },
  },
  {
    id: "water",
    tr: "Su",
    en: "Water",
    category: "need",
    weights: { morning: 0.95, afternoon: 1, evening: 0.95, night: 0.9 },
  },
  {
    id: "hygiene",
    tr: "Temizlik",
    en: "Hygiene",
    category: "need",
    weights: { morning: 1, afternoon: 1, evening: 1, night: 1 },
  },
  {
    id: "cold",
    tr: "Soğuk",
    en: "Cold",
    category: "need",
    weights: { morning: 0.35, afternoon: 0.55, evening: 0.4, night: 0.25 },
  },
  {
    id: "hot",
    tr: "Sıcak",
    en: "Hot",
    category: "need",
    weights: { morning: 0.45, afternoon: 0.5, evening: 0.35, night: 0.2 },
  },
  {
    id: "breakfast",
    tr: "Kahvaltı",
    en: "Breakfast",
    category: "meal",
    weights: { morning: 1, afternoon: 0.08, evening: 0.02, night: 0 },
  },
  {
    id: "tea",
    tr: "Çay",
    en: "Tea",
    category: "meal",
    weights: { morning: 0.98, afternoon: 0.55, evening: 0.85, night: 0.05 },
  },
  {
    id: "coffee",
    tr: "Kahve",
    en: "Coffee",
    category: "meal",
    weights: { morning: 0.9, afternoon: 0.4, evening: 0.15, night: 0 },
  },
  {
    id: "food",
    tr: "Yemek",
    en: "Food",
    category: "meal",
    weights: { morning: 0.25, afternoon: 1, evening: 0.9, night: 0.1 },
  },
  {
    id: "medicine",
    tr: "İlaç",
    en: "Medicine",
    category: "need",
    weights: { morning: 0.88, afternoon: 0.7, evening: 0.75, night: 0.45 },
  },
  {
    id: "sleep",
    tr: "Uyku",
    en: "Sleep",
    category: "comfort",
    weights: { morning: 0.05, afternoon: 0.15, evening: 0.7, night: 1 },
  },
  {
    id: "light",
    tr: "Işık",
    en: "Light",
    category: "comfort",
    weights: { morning: 0.35, afternoon: 0.2, evening: 0.8, night: 0.98 },
  },
  {
    id: "bed",
    tr: "Yatak",
    en: "Bed",
    category: "comfort",
    weights: { morning: 0.4, afternoon: 0.25, evening: 0.55, night: 0.92 },
  },
  {
    id: "blanket",
    tr: "Battaniye",
    en: "Blanket",
    category: "comfort",
    weights: { morning: 0.15, afternoon: 0.1, evening: 0.5, night: 0.9 },
  },
  {
    id: "pillow",
    tr: "Yastık",
    en: "Pillow",
    category: "comfort",
    weights: { morning: 0.45, afternoon: 0.2, evening: 0.4, night: 0.7 },
  },
  {
    id: "window",
    tr: "Pencere",
    en: "Window",
    category: "comfort",
    weights: { morning: 0.7, afternoon: 0.45, evening: 0.3, night: 0.1 },
  },
  {
    id: "tv",
    tr: "TV",
    en: "TV",
    category: "social",
    weights: { morning: 0.2, afternoon: 0.75, evening: 0.88, night: 0.25 },
  },
  {
    id: "quiet",
    tr: "Sessiz",
    en: "Quiet",
    category: "comfort",
    weights: { morning: 0.25, afternoon: 0.4, evening: 0.45, night: 0.75 },
  },
  {
    id: "family",
    tr: "Aile",
    en: "Family",
    category: "social",
    weights: { morning: 0.4, afternoon: 0.5, evening: 0.8, night: 0.35 },
  },
  {
    id: "thanks",
    tr: "Teşekkür",
    en: "Thanks",
    category: "social",
    weights: { morning: 0.55, afternoon: 0.55, evening: 0.55, night: 0.4 },
  },
  {
    id: "come",
    tr: "Gel",
    en: "Come",
    category: "social",
    weights: { morning: 0.45, afternoon: 0.5, evening: 0.5, night: 0.55 },
  },
  {
    id: "wait",
    tr: "Bekle",
    en: "Wait",
    category: "social",
    weights: { morning: 0.4, afternoon: 0.45, evening: 0.4, night: 0.3 },
  },
  {
    id: "open",
    tr: "Aç",
    en: "Open",
    category: "comfort",
    weights: { morning: 0.55, afternoon: 0.5, evening: 0.55, night: 0.45 },
  },
  {
    id: "close",
    tr: "Kapat",
    en: "Close",
    category: "comfort",
    weights: { morning: 0.5, afternoon: 0.55, evening: 0.6, night: 0.5 },
  },
  {
    id: "more",
    tr: "Daha",
    en: "More",
    category: "social",
    weights: { morning: 0.52, afternoon: 0.55, evening: 0.5, night: 0.4 },
  },
  {
    id: "stop",
    tr: "Dur",
    en: "Stop",
    category: "social",
    weights: { morning: 0.5, afternoon: 0.5, evening: 0.5, night: 0.5 },
  },
  {
    id: "tired",
    tr: "Yorgun",
    en: "Tired",
    category: "need",
    weights: { morning: 0.2, afternoon: 0.55, evening: 0.7, night: 0.65 },
  },
  {
    id: "adjust",
    tr: "Düzelt",
    en: "Adjust",
    category: "comfort",
    weights: { morning: 0.5, afternoon: 0.45, evening: 0.55, night: 0.8 },
  },
];

export const CORE_IDS = ["yes", "no", "help", "pain", "toilet", "water", "hygiene"] as const;

export const CONTEXT_SLOTS = 8;
